name: Docker Image CI

on:
  push:
    branches: [ master ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker-compose build

    - name: List images
      run: docker images

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
        
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          musicbrainz-docker_musicbrainz
          musicbrainz-docker_indexer
          musicbrainz-docker_db
          musicbrainz-docker_mq
          musicbrainz-docker_search
        tags: latest

    - name: List images
      run: docker images
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: ${{ steps.meta.outputs.tags }}
