name: Build and publish Docker image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build images
      run: docker-compose build

    - name: List images
      run: docker images
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: yyoung01
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: y-young
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag and push images
      run: |
        set -x
        VERSION=$(awk '/MUSICBRAINZ_SERVER_VERSION=/' build/musicbrainz/Dockerfile | cut -d'=' -f2)
        echo "Version: $VERSION"
        images=()
        for registry in "yyoung01" "ghcr.io/y-young"
        do
            for tag in "latest" $VERSION
            do
                for image in "musicbrainz-docker_musicbrainz" "musicbrainz-docker_indexer" "musicbrainz-docker_mq"
                do
                    docker tag $image:latest $registry/$image:$tag
                    images+=("$registry/$image:$tag")
                done
            done
            for tag in "12" $VERSION
            do
                docker tag musicbrainz-docker_db:12 $registry/musicbrainz-docker_db:$tag
                images+=("$registry/musicbrainz-docker_db:$tag")
            done
            for tag in "3.4.2" $VERSION
            do
                docker tag musicbrainz-docker_search:3.4.2 $registry/musicbrainz-docker_search:$tag
                images+=("$registry/musicbrainz-docker_search:$tag")
            done
        done
        for image in "${images[@]}"
        do
            docker push $image
        done
