name: Docker Image CI

on:
  push:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  TAG_PREFIX: ghcr.io/${{ github.actor }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build images
      run: docker-compose build

    - name: List images
      run: docker images

    - name: Log into registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
        
    - name: Tag images
      run: |
        docker tag musicbrainz-docker_musicbrainz:latest ${{ env.TAG_PREFIX }}/musicbrainz-docker_musicbrainz:latest
        docker tag musicbrainz-docker_indexer:latest ${{ env.TAG_PREFIX }}/musicbrainz-docker_indexer:latest
        docker tag musicbrainz-docker_db:12 ${{ env.TAG_PREFIX }}/musicbrainz-docker_db:12
        docker tag musicbrainz-docker_mq:latest ${{ env.TAG_PREFIX }}/musicbrainz-docker_mq:latest
        docker tag musicbrainz-docker_search:3.4.2 ${{ env.TAG_PREFIX }}/musicbrainz-docker_search:3.4.2

    - name: Push images to registry
      run: |
        docker push ${{ env.TAG_PREFIX }}/musicbrainz-docker_musicbrainz:latest
        docker push ${{ env.TAG_PREFIX }}/musicbrainz-docker_indexer:latest
        docker push ${{ env.TAG_PREFIX }}/musicbrainz-docker_db:12
        docker push ${{ env.TAG_PREFIX }}/musicbrainz-docker_mq:latest  
           docker push ${{ env.TAG_PREFIX }}/musicbrainz-docker_search:3.4.2
